-- Seed data for dynamic EXPLAIN demos against MySQL 8+.
-- Apply before analyzing examples/mixed_mysql.sql or examples/bad_queries.sql.

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  amount DECIMAL(10, 2)
);

INSERT INTO users (email)
SELECT CONCAT('user_', seq, '@example.com')
FROM (
  SELECT a.N + b.N * 10 + 1 AS seq
  FROM
    (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
     UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
    (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
     UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b
) numbers;

INSERT INTO orders (user_id, amount)
SELECT FLOOR(1 + RAND() * 100), ROUND(RAND() * 100, 2)
FROM users u
CROSS JOIN (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) x;
