/**
 * Copyright (c) 2026 sql-optima contributors
 * SPDX-License-Identifier: MIT
 */

/**
 * Formats static and dynamic analysis results into a structured GitHub Markdown report.
 */

/**
 * Escape text for use inside a GitHub Markdown table cell.
 * Backslashes first, then pipes, so escaped pipes stay intact.
 * @param {string} value
 * @returns {string}
 */
function escapeMarkdownTableCell(value) {
  return String(value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\|/g, '\\|');
}

/**
 * Generates a GitHub Step Summary Markdown string.
 *
 * @param {Object} options
 * @param {string} options.engine - Database engine used ('postgres' | 'mysql').
 * @param {string} options.sqlContent - Raw SQL query or schema tested.
 * @param {Array<Object>} options.staticIssues - Issues detected by static AST parsing.
 * @param {Object} options.dynamicResult - Result object from dynamic EXPLAIN execution.
 * @returns {string} Markdown formatted report.
 */
function generateMarkdownReport({ engine, sqlContent, staticIssues = [], dynamicResult = {} }) {
  const {
    executed = false,
    executionTimeMs,
    planningTimeMs,
    totalCost,
    issues: dynamicIssues = [],
    error: dynamicError,
    reason: dynamicReason,
  } = dynamicResult;

  const allIssues = [...staticIssues, ...dynamicIssues];

  // Helper to count issues by severity
  const getSeverityBadge = (severity) => {
    switch (severity?.toUpperCase()) {
      case 'CRITICAL':
        return '🔴 **CRITICAL**';
      case 'HIGH':
        return '🟠 **HIGH**';
      case 'MEDIUM':
        return '🟡 **MEDIUM**';
      case 'LOW':
        return '🔵 **LOW**';
      default:
        return 'ℹ️ **INFO**';
    }
  };

  let markdown = `## 🚀 SQL Optima Report\n\n`;

  // 1. Overview Table
  markdown += `### 📊 Summary Overview\n\n`;
  markdown += `| Metric | Value |\n`;
  markdown += `| :--- | :--- |\n`;
  markdown += `| **Database Engine** | \`${engine.toUpperCase()}\` |\n`;
  markdown += `| **Static Issues Found** | \`${staticIssues.length}\` |\n`;
  markdown += `| **Dynamic Issues Found** | \`${dynamicIssues.length}\` |\n`;

  if (executed) {
    markdown += `| **Execution Time** | \`${executionTimeMs != null ? `${executionTimeMs} ms` : 'N/A'}\` |\n`;
    markdown += `| **Planning Time** | \`${planningTimeMs != null ? `${planningTimeMs} ms` : 'N/A'}\` |\n`;
    markdown += `| **Total Estimated Cost** | \`${totalCost != null ? totalCost : 'N/A'}\` |\n`;
  } else if (dynamicReason) {
    markdown += `| **Dynamic Execution** | ℹ️ ${dynamicReason} |\n`;
  } else if (dynamicError) {
    markdown += `| **Dynamic Execution** | ⚠️ Execution Error |\n`;
  }

  markdown += `\n---\n\n`;

  // 2. Tested SQL Snippet Collapsible Block
  markdown += `<details>\n<summary>🔍 <b>View Analyzed SQL Code</b></summary>\n\n`;
  markdown += `\`\`\`sql\n${sqlContent.trim()}\n\`\`\`\n\n`;
  markdown += `</details>\n\n---\n\n`;

  // 3. Dynamic Execution Error Notice (if any)
  if (dynamicError) {
    markdown += `### ⚠️ Dynamic Execution Warning\n\n`;
    markdown += `> ${dynamicError}\n\n`;
  }

  // 4. Detected Issues & Recommendations
  markdown += `### 💡 Findings & Optimization Suggestions\n\n`;

  if (allIssues.length === 0) {
    markdown += `🎉 **No issues or anti-patterns detected! Your SQL schema and query look optimal.**\n\n`;
  } else {
    markdown += `| Severity | Issue Type | Message & Recommendation |\n`;
    markdown += `| :---: | :--- | :--- |\n`;

    allIssues.forEach((issue) => {
      const badge = getSeverityBadge(issue.severity);
      const message = escapeMarkdownTableCell(issue.message);
      const suggestion = issue.suggestion
        ? `<br>👉 *${escapeMarkdownTableCell(issue.suggestion)}*`
        : '';

      markdown += `| ${badge} | \`${issue.type}\` | ${message}${suggestion} |\n`;
    });

    markdown += `\n`;
  }

  // 5. Raw EXPLAIN JSON Collapsible Block (if executed)
  if (executed && dynamicResult.rawPlan) {
    markdown += `<details>\n<summary>📄 <b>View Raw EXPLAIN Plan (JSON)</b></summary>\n\n`;
    markdown += `\`\`\`json\n${JSON.stringify(dynamicResult.rawPlan, null, 2)}\n\`\`\`\n\n`;
    markdown += `</details>\n\n`;
  }

  markdown += `---\n*Generated by [SQL Optima Action](https://github.com/ale94lko/sql-optima)*\n`;

  return markdown;
}

module.exports = {
  generateMarkdownReport,
  escapeMarkdownTableCell,
};

